[package]
name = "terminal_toolbox"
version = "0.0.2"
edition = "2021"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.10"
console = "0.15.0"
# dialoguer = "0.10.0"
