[package]
name = "term_tools"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.10"
console = "0.15.0"
dialoguer = "0.10.0"
